### ISSUE TITLE
Support canonical chmod.

### ISSUE THREAD

**Issue by envygeeks** [aki77/atom-chmod#1]
It would be awesome if you would support canonical chmod (`a-rwx,og+rx`.)  I personally have always had a love for the canonical form.

**Comment by aki77** [comment]
It's difficult but I'll try to implement this. Very low priority. :sweat:

**Comment by envygeeks** [comment]
You'll have to stat the file to get the current permissions of course to do it but after that it's a matter of simply converting that to numbers.  So say I stat the file and it currently has 644.

```
r=4
w=2
x=1
```

So at 644 then it converts to `a-0,og+5` which converts to `655` and that's what you send.
I would send a PR for it but honestly I don't know CoffeeScript.  I still write my apps in pure JS.
